env:
  ANKA_IMAGE_NAME: macos-10.12-xcode-8.3.3
  XCODE_DESTINATION: platform=iOS Simulator,name=iPhone 7,OS=10.3.1

steps:
  - label: "Build"
    command: "./build.sh"

  - wait
  - label: "Unit Tests"
    command: "./test.sh 'Buildkite Anka DemoTests'"

  - wait
  - label: "UI Tests"
    command: "./test.sh 'Buildkite Anka DemoUITests'"
